import { Video, Profile, Category, Tag, Comment, Report, AdminAction } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-tech', name: 'Technology & Code', slug: 'technology', description: 'Software engineering, hardware, systems design, and tutorials', icon: 'Code', video_count: 14 },
  { id: 'cat-cinema', name: 'Cinema & VFX', slug: 'cinema-vfx', description: 'Cinematic visual effects, storytelling, direction, and rendering', icon: 'Film', video_count: 12 },
  { id: 'cat-gaming', name: 'Game Dev & Play', slug: 'gaming', description: 'Game engines, indie gameplay, mechanics, and design', icon: 'Gamepad2', video_count: 9 },
  { id: 'cat-science', name: 'Science & Cosmos', slug: 'science', description: 'Astrophysics, biology, deep space exploration, and mathematics', icon: 'Atom', video_count: 8 },
  { id: 'cat-music', name: 'Music & Audio', slug: 'music', description: 'Original scoring, modular synthesis, sound design, and live performance', icon: 'Music', video_count: 11 },
  { id: 'cat-creative', name: 'Creative Arts', slug: 'creative-arts', description: '3D modeling, typography, digital painting, and architectural art', icon: 'Palette', video_count: 7 },
  { id: 'cat-travel', name: 'Nature & Travel', slug: 'nature-travel', description: 'Expeditions, wilderness time-lapses, drone cinematography, and ecology', icon: 'Compass', video_count: 6 },
];

export const INITIAL_TAGS: Tag[] = [
  { id: 'tag-1', name: 'WebDev', slug: 'webdev' },
  { id: 'tag-2', name: 'React', slug: 'react' },
  { id: 'tag-3', name: 'Blender', slug: 'blender' },
  { id: 'tag-4', name: '4K', slug: '4k' },
  { id: 'tag-5', name: 'Synthesizer', slug: 'synthesizer' },
  { id: 'tag-6', name: 'GameEngine', slug: 'gameengine' },
  { id: 'tag-7', name: 'Astronomy', slug: 'astronomy' },
  { id: 'tag-8', name: 'Documentary', slug: 'documentary' },
  { id: 'tag-9', name: 'OpenSource', slug: 'opensource' },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-admin',
    username: 'admin',
    display_name: 'Platform Overseer',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&auto=format&fit=crop&q=80',
    bio: 'StreamSphere Trust & Safety lead and core platform administrator.',
    website: 'https://streamsphere.org',
    role: 'admin',
    is_verified: true,
    is_suspended: false,
    subscriber_count: 14200,
    total_views: 948000,
    created_at: '2024-01-10T00:00:00.000Z',
  },
  {
    id: 'creator-aria',
    username: 'ariachen',
    display_name: 'Aria Chen',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    bio: 'Full-stack software architect & graphics programmer exploring WebGL, Rust, and distributed architectures.',
    website: 'https://ariachen.dev',
    role: 'creator',
    is_verified: true,
    is_suspended: false,
    subscriber_count: 48200,
    total_views: 1240500,
    created_at: '2024-02-15T00:00:00.000Z',
  },
  {
    id: 'creator-marcus',
    username: 'marcus_vfx',
    display_name: 'Marcus Vance',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    bio: 'Award-winning cinematographer and procedural 3D visual artist creating open film projects.',
    website: 'https://marcusvance.art',
    role: 'creator',
    is_verified: true,
    is_suspended: false,
    subscriber_count: 62400,
    total_views: 2840000,
    created_at: '2024-01-20T00:00:00.000Z',
  },
  {
    id: 'creator-elena',
    username: 'elenasound',
    display_name: 'Elena Rostova',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    bio: 'Electronic music producer, sound designer, and vintage modular synthesizer collector.',
    website: 'https://elenasound.fm',
    role: 'creator',
    is_verified: true,
    is_suspended: false,
    subscriber_count: 31500,
    total_views: 789000,
    created_at: '2024-03-01T00:00:00.000Z',
  },
  {
    id: 'creator-kai',
    username: 'kaitanaka',
    display_name: 'Kai Tanaka',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&auto=format&fit=crop&q=80',
    bio: 'Independent game director building stylized open-world voxel engines and physics systems.',
    role: 'creator',
    is_verified: false,
    is_suspended: false,
    subscriber_count: 19800,
    total_views: 512000,
    created_at: '2024-03-12T00:00:00.000Z',
  },
];

// Open-access lawful creative commons video streams (reliable HTML5 / MP4 / HLS streams)
export const INITIAL_VIDEOS: Video[] = [
  {
    id: 'vid-101',
    bunny_video_id: 'bunny-cosmic-drift',
    title: 'Cosmic Horizons: Deep Field Astrophotography in 4K',
    slug: 'cosmic-horizons-deep-field-astrophotography-4k',
    description: 'An expansive visual journey through newly processed deep space nebulae, recorded with narrowband multi-spectral filters over 140 cumulative exposure hours. Original score composed on analog modular synths.',
    thumbnail_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    duration: 642, // 10m 42s
    category_id: 'cat-science',
    creator_id: 'creator-marcus',
    visibility: 'public',
    moderation_status: 'published',
    is_age_restricted: false,
    allow_comments: true,
    views: 184520,
    likes_count: 12430,
    comments_count: 342,
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    created_at: '2025-01-14T10:00:00.000Z',
  },
  {
    id: 'vid-102',
    bunny_video_id: 'bunny-distributed-systems',
    title: 'Architecting Scalable Real-Time Video Platforms from Scratch',
    slug: 'architecting-scalable-real-time-video-platforms-scratch',
    description: 'Deep dive into edge CDN caching, Bunny Stream adaptive HLS transcoding, chunked direct uploads, and idempotent view counting models with PostgreSQL RLS security.',
    thumbnail_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    duration: 1140, // 19m 00s
    category_id: 'cat-tech',
    creator_id: 'creator-aria',
    visibility: 'public',
    moderation_status: 'published',
    is_age_restricted: false,
    allow_comments: true,
    views: 94310,
    likes_count: 8120,
    comments_count: 189,
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    created_at: '2025-01-20T14:30:00.000Z',
  },
  {
    id: 'vid-103',
    bunny_video_id: 'bunny-modular-ambient',
    title: 'Ambient Modular Synthesis: Live Generative Patch Walkthrough',
    slug: 'ambient-modular-synthesis-live-generative-patch',
    description: 'Building an evolving polyrhythmic ambient soundscape using Eurorack CV modulators, tape loop saturation, and stereo bucket-brigade analog delay.',
    thumbnail_url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80',
    duration: 820,
    category_id: 'cat-music',
    creator_id: 'creator-elena',
    visibility: 'public',
    moderation_status: 'published',
    is_age_restricted: false,
    allow_comments: true,
    views: 63200,
    likes_count: 5410,
    comments_count: 98,
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    created_at: '2025-01-25T18:00:00.000Z',
  },
  {
    id: 'vid-104',
    bunny_video_id: 'bunny-voxel-engine',
    title: 'Building a Voxel Lighting Engine with Compute Shaders in Rust',
    slug: 'building-voxel-lighting-engine-compute-shaders-rust',
    description: 'Step-by-step breakdown of implementing octree sparse voxel directed acyclic graphs (SVDAG) and real-time ray-traced shadows on modern GPUs.',
    thumbnail_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    duration: 1350,
    category_id: 'cat-gaming',
    creator_id: 'creator-kai',
    visibility: 'public',
    moderation_status: 'published',
    is_age_restricted: false,
    allow_comments: true,
    views: 42100,
    likes_count: 3890,
    comments_count: 145,
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    created_at: '2025-02-01T09:15:00.000Z',
  },
  {
    id: 'vid-105',
    bunny_video_id: 'bunny-cinematic-lighting',
    title: 'Cinematography Masterclass: Painting with Volumetric Light',
    slug: 'cinematography-masterclass-painting-volumetric-light',
    description: 'Exploring practical lighting techniques on independent sets, haze distribution, negative fill, and shaping cinematic depth without expensive rigs.',
    thumbnail_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&auto=format&fit=crop&q=80',
    duration: 980,
    category_id: 'cat-cinema',
    creator_id: 'creator-marcus',
    visibility: 'public',
    moderation_status: 'published',
    is_age_restricted: false,
    allow_comments: true,
    views: 112000,
    likes_count: 9400,
    comments_count: 260,
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    created_at: '2025-02-05T12:00:00.000Z',
  },
  {
    id: 'vid-106',
    bunny_video_id: 'bunny-react-performance',
    title: 'High-Performance React: Elimination of Cascading Rerenders',
    slug: 'high-performance-react-elimination-cascading-rerenders',
    description: 'Practical profiling with React DevTools and Chrome Performance tab to identify micro-bottlenecks, memoization anti-patterns, and optimal state collocation.',
    thumbnail_url: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format&fit=crop&q=80',
    duration: 755,
    category_id: 'cat-tech',
    creator_id: 'creator-aria',
    visibility: 'public',
    moderation_status: 'published',
    is_age_restricted: false,
    allow_comments: true,
    views: 78500,
    likes_count: 6730,
    comments_count: 142,
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    created_at: '2025-02-10T16:20:00.000Z',
  },
  {
    id: 'vid-107',
    bunny_video_id: 'bunny-norway-fjords',
    title: 'Silent Wilderness: Aerial Perspectives Across the Arctic Fjords',
    slug: 'silent-wilderness-aerial-perspectives-arctic-fjords',
    description: 'Cinematic drone odyssey through sub-zero glacial valleys, midnight sun coastlines, and pristine alpine waterways. Recorded in uncompressed ProRes RAW.',
    thumbnail_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
    duration: 520,
    category_id: 'cat-travel',
    creator_id: 'creator-marcus',
    visibility: 'public',
    moderation_status: 'published',
    is_age_restricted: false,
    allow_comments: true,
    views: 149300,
    likes_count: 11200,
    comments_count: 180,
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    created_at: '2025-02-14T11:00:00.000Z',
  },
  {
    id: 'vid-108',
    bunny_video_id: 'bunny-pending-upload',
    title: 'Procedural Terrain Generator [Awaiting Moderation]',
    slug: 'procedural-terrain-generator-awaiting-moderation',
    description: 'A demonstration of multi-threaded simplex noise heightmap generation with hydraulic erosion simulation.',
    thumbnail_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    duration: 410,
    category_id: 'cat-gaming',
    creator_id: 'creator-kai',
    visibility: 'public',
    moderation_status: 'pending_review',
    is_age_restricted: false,
    allow_comments: true,
    views: 12,
    likes_count: 2,
    comments_count: 0,
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    created_at: '2025-02-20T08:00:00.000Z',
  },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'com-1',
    video_id: 'vid-101',
    user_id: 'creator-aria',
    user: INITIAL_PROFILES[1],
    content: 'The color grading on the emission nebulae around 04:20 is extraordinary. Did you apply custom LUTs or color match manually in DaVinci Resolve?',
    likes_count: 24,
    is_hidden: false,
    created_at: '2025-01-15T11:30:00.000Z',
  },
  {
    id: 'com-2',
    video_id: 'vid-101',
    user_id: 'creator-elena',
    user: INITIAL_PROFILES[3],
    content: 'The low-frequency drone in the soundtrack compliments the expansive space shots so well. Absolutely mesmerizing work!',
    likes_count: 18,
    is_hidden: false,
    created_at: '2025-01-15T13:45:00.000Z',
  },
  {
    id: 'com-3',
    video_id: 'vid-102',
    user_id: 'creator-kai',
    user: INITIAL_PROFILES[4],
    content: 'Brilliant explanation of chunked direct uploads to Bunny CDN without bottlenecking the central API layer. Will definitely implement this pattern.',
    likes_count: 15,
    is_hidden: false,
    created_at: '2025-01-21T09:12:00.000Z',
  },
];

export const INITIAL_REPORTS: Report[] = [
  {
    id: 'rep-1',
    reporter_id: 'creator-aria',
    video_id: 'vid-108',
    reason: 'spam',
    description: 'Automated test upload requiring verification of licensing tags.',
    status: 'pending',
    created_at: '2025-02-20T10:00:00.000Z',
  },
];

export const INITIAL_AUDIT_LOGS: AdminAction[] = [
  {
    id: 'log-1',
    admin_id: 'user-admin',
    admin: INITIAL_PROFILES[0],
    action: 'video_approve',
    target_type: 'video',
    target_id: 'vid-107',
    target_name: 'Silent Wilderness: Aerial Perspectives Across the Arctic Fjords',
    details: { note: 'Verified lawful consensual footage and appropriate content tagging.' },
    ip_address: '192.168.1.1',
    created_at: '2025-02-14T11:05:00.000Z',
  },
  {
    id: 'log-2',
    admin_id: 'user-admin',
    admin: INITIAL_PROFILES[0],
    action: 'creator_verify',
    target_type: 'user',
    target_id: 'creator-aria',
    target_name: 'Aria Chen',
    details: { badge: 'Verified Creator' },
    ip_address: '192.168.1.1',
    created_at: '2025-02-10T15:00:00.000Z',
  },
];
