import React, { useEffect, useRef, useState } from 'react';
import { Upload, X, Link as LinkIcon, Loader2, RefreshCw } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { videoService } from '../services/videoService';
import type { Category } from '../types';

type UploadMode = 'uqload' | 'doodstream' | 'filemoon' | 'streamtape' | 'embed';
const getEmbedSource = (value: string) => { const trimmed = value.trim(); const iframeMatch = trimmed.match(/<iframe[^>]+src=["']([^"']+)["']/i); return iframeMatch?.[1] || trimmed; };
const extractUqloadFile = (payload: any) => { const file = payload?.files?.[0] || payload?.result?.[0] || payload?.result || payload?.file || payload; return { fileCode: file?.filecode || file?.fileCode || payload?.filecode || payload?.fileCode || null, thumbnailUrl: file?.player_img || file?.playerImg || file?.thumbnail || file?.thumbnail_url || file?.snapshot || file?.snapshot_url || payload?.player_img || payload?.thumbnail_url || null }; };
const formatUploadError = (data: any, providerName: string, status: number) => { const primary = String(data?.error || data?.message || `${providerName} upload failed (${status}).`); const parts = [primary]; if (data?.upstreamStatus) parts.push(`Upstream HTTP ${data.upstreamStatus}`); if (data?.requestId) parts.push(`Request ID: ${data.requestId}`); if (data?.chunk !== undefined && data?.totalChunks) parts.push(`Chunk ${Number(data.chunk) + 1}/${data.totalChunks}`); const upstreamMessage = data?.details?.error?.message; const upstreamCode = data?.details?.error?.code; if (upstreamCode || upstreamMessage) parts.push(`FileMoon ${[upstreamCode, upstreamMessage].filter(Boolean).join(': ')}`); const raw = typeof data?.details?.raw === 'string' ? data.details.raw.trim() : ''; if (raw && !parts.some((part) => part.includes(raw))) parts.push(`Upstream response: ${raw.slice(0, 500)}`); return parts.join(' • '); };

export default function UploadPage() {
  const { user, isAdmin } = useAuth(); const [uploadMode, setUploadMode] = useState<UploadMode>('uqload'); const [filemoonAccount, setFilemoonAccount] = useState<'1' | '2'>('1'); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [categoryId, setCategoryId] = useState(''); const [categories, setCategories] = useState<Category[]>([]); const [selectedFile, setSelectedFile] = useState<File | null>(null); const [embedInput, setEmbedInput] = useState(''); const [isDragging, setIsDragging] = useState(false); const [isUploading, setIsUploading] = useState(false); const [isSyncing, setIsSyncing] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [embedLink, setEmbedLink] = useState(''); const fileInputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { videoService.getCategories().then(setCategories).catch(() => setCategories([])); }, []);
  const handleFileSelect = (file?: File) => { setError(''); setSuccess(''); setEmbedLink(''); if (!file) return; if (!file.type.startsWith('video/')) { setError('Please select a valid video file.'); return; } if (file.size > 1024 * 1024 * 1024) { setError('Video file must be 1GB or smaller.'); return; } setSelectedFile(file); };
  const handleDrop = (event: React.DragEvent<HTMLDivElement>) => { event.preventDefault(); setIsDragging(false); handleFileSelect(event.dataTransfer.files?.[0]); };
  const syncFileMoon = async (account: '1' | '2') => { try { setIsSyncing(true); setFilemoonAccount(account); setError(''); setSuccess(''); const session = await import('../lib/supabase').then(({ supabase }) => supabase.auth.getSession()); const token = session.data.session?.access_token; if (!token) throw new Error('Your session has expired. Please sign in again.'); const response = await fetch('/api/filemoon/sync', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ filemoon_account: account }) }); let data: any = {}; try { data = await response.json(); } catch {} if (!response.ok) throw new Error(data?.error || `FileMoon Account ${account} sync failed (${response.status}).`); setSuccess(`FileMoon Account ${account} sync complete: ${data.imported || 0} imported, ${data.updated || 0} updated, ${data.total || 0} files found.`); } catch (err) { setError(err instanceof Error ? err.message : 'FileMoon sync failed.'); } finally { setIsSyncing(false); } };
  const uploadMultipart = async (endpoint: string, token: string, providerName: string, account?: '1' | '2') => { if (!selectedFile) throw new Error('Please select a video file.'); const formData = new FormData(); formData.append('file', selectedFile); formData.append('title', title.trim()); formData.append('description', description.trim()); formData.append('category_id', categoryId); if (account) formData.append('filemoon_account', account); return await new Promise<any>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open('POST', endpoint); xhr.setRequestHeader('Authorization', `Bearer ${token}`); xhr.upload.onprogress = (event) => { if (event.lengthComputable) setSuccess(`Uploading to ${providerName}... ${Math.round((event.loaded / event.total) * 100)}%`); }; xhr.onload = () => { let data: any = {}; try { data = JSON.parse(xhr.responseText || '{}'); } catch { data = { raw: xhr.responseText || '' }; } if (xhr.status >= 200 && xhr.status < 300) resolve(data); else reject(new Error(formatUploadError(data, providerName, xhr.status))); }; xhr.onerror = () => reject(new Error(`Network error while uploading to ${providerName}.`)); xhr.send(formData); }); };
  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault(); setError(''); setSuccess(''); setEmbedLink(''); if (!user) { setError('Please sign in before uploading a video.'); return; } if (!isAdmin) { setError('Admin access required for video uploads.'); return; } if (!title.trim()) { setError('Please enter a title.'); return; }
    const isAnyEmbed = uploadMode === 'embed'; if (isAnyEmbed ? !embedInput.trim() : !selectedFile) { setError(isAnyEmbed ? 'Please enter an embed URL or iframe code.' : 'Please select a video file.'); return; }
    try {
      setIsUploading(true); const session = await import('../lib/supabase').then(({ supabase }) => supabase.auth.getSession()); const token = session.data.session?.access_token; if (!token) throw new Error('Your session has expired. Please sign in again.');
      let providerId = ''; let videoUrl = ''; let thumbnailUrl = ''; let serverVideoId = '';
      if (isAnyEmbed) { videoUrl = getEmbedSource(embedInput); providerId = videoUrl; }
      else if (uploadMode === 'streamtape') { const result = await uploadMultipart('/api/streamtape/proxy-upload', token, 'Streamtape'); providerId = String(result.fileId || result.providerId || ''); if (!providerId) throw new Error('Streamtape did not return a file ID.'); videoUrl = String(result.embedUrl || `https://streamtape.com/e/${encodeURIComponent(providerId)}`); thumbnailUrl = String(result.thumbnailUrl || ''); }
      else if (uploadMode === 'filemoon') { const result = await uploadMultipart('/api/filemoon/proxy-upload', token, 'FileMoon Account ' + filemoonAccount, filemoonAccount); providerId = String(result.fileId || result.providerId || ''); if (!providerId) throw new Error('FileMoon did not return a file ID.'); videoUrl = String(result.embedUrl || result.videoUrl || `https://filemoon.org/${encodeURIComponent(providerId)}/embed`); thumbnailUrl = String(result.thumbnailUrl || ''); serverVideoId = String(result.videoId || ''); if (!serverVideoId) throw new Error('FileMoon uploaded successfully, but Supabase video record was not created.'); }
      else if (uploadMode === 'doodstream') { const result = await uploadMultipart('/api/doodstream/proxy-upload', token, 'DoodStream'); providerId = String(result.fileCode || result.providerId || ''); if (!providerId) throw new Error('DoodStream did not return a file code.'); videoUrl = String(result.embedUrl || result.videoUrl || `https://dood.to/e/${encodeURIComponent(providerId)}`); thumbnailUrl = String(result.thumbnailUrl || ''); }
      else { const result = await uploadMultipart('/api/uqload/proxy-upload', token, 'UQLOAD'); const extracted = extractUqloadFile(result); providerId = String(extracted.fileCode || ''); if (!providerId) throw new Error('UQLOAD did not return a file code.'); videoUrl = `https://uqload.vc/e/${providerId}`; thumbnailUrl = extracted.thumbnailUrl || `/api/uqload/thumbnail/${encodeURIComponent(providerId)}`; }
      const created = serverVideoId ? { id: serverVideoId } : await videoService.createVideo({ title:title.trim(), description:description.trim(), category_id:categoryId || undefined, creator_id:user.id, video_url:videoUrl, thumbnail_url:thumbnailUrl, preview_animation_url:'', provider:uploadMode, provider_id:providerId, ...(uploadMode === 'uqload' ? { uqload_filecode:providerId } : {}), is_published:true });
      const localEmbed = `${window.location.origin}/embed/${created.id}`; setEmbedLink(localEmbed); setSuccess(isAnyEmbed ? 'External embed link added successfully.' : `${uploadMode === 'streamtape' ? 'Streamtape' : uploadMode === 'filemoon' ? `FileMoon Account ${filemoonAccount}` : uploadMode === 'doodstream' ? 'DoodStream' : 'UQLOAD'} upload completed successfully and saved to Supabase.`); setTitle(''); setDescription(''); setCategoryId(''); setSelectedFile(null); setEmbedInput('');
    } catch (err) { setError(err instanceof Error ? err.message : 'Upload failed.'); } finally { setIsUploading(false); }
  };
  const resetMode = (mode: UploadMode) => { setUploadMode(mode); setError(''); setSuccess(''); setEmbedLink(''); setSelectedFile(null); setEmbedInput(''); };
  const providerLabel = uploadMode === 'streamtape' ? 'Streamtape' : uploadMode === 'filemoon' ? `FileMoon Account ${filemoonAccount}` : uploadMode === 'doodstream' ? 'DoodStream' : uploadMode === 'uqload' ? 'UQLOAD' : 'Any Embed Link';
  return (
    <div className="min-h-screen bg-black text-white p-6 md:p-10"><div className="max-w-3xl mx-auto space-y-6">
      <div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-black">Upload Video</h1><p className="text-sm text-zinc-400 mt-1">Admin-only video upload providers.</p></div>{isAdmin && <div className="flex flex-wrap gap-2 justify-end"><button type="button" onClick={() => syncFileMoon('1')} disabled={isSyncing || isUploading} className="px-4 py-2 rounded-xl border border-white/10 bg-[#0a0a0a] text-sm font-bold text-zinc-200 hover:bg-white/10 disabled:opacity-50 flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${isSyncing && filemoonAccount === '1' ? 'animate-spin' : ''}`} />{isSyncing && filemoonAccount === '1' ? 'Syncing...' : 'Sync Account 1'}</button><button type="button" onClick={() => syncFileMoon('2')} disabled={isSyncing || isUploading} className="px-4 py-2 rounded-xl bg-amber-500 text-black text-sm font-black hover:bg-amber-400 disabled:opacity-50 flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${isSyncing && filemoonAccount === '2' ? 'animate-spin' : ''}`} />{isSyncing && filemoonAccount === '2' ? 'Syncing...' : 'Sync Account 2'}</button></div>}</div>
      <div className="flex flex-wrap bg-[#0a0a0a] border border-white/10 rounded-xl p-1">{(['uqload','doodstream','filemoon','streamtape','embed'] as UploadMode[]).map((mode) => <button key={mode} type="button" onClick={() => resetMode(mode)} className={`flex-1 min-w-[130px] py-2 text-sm font-semibold rounded-lg transition-colors ${uploadMode === mode ? 'bg-amber-500/20 text-amber-400' : 'text-zinc-400 hover:text-white'}`}>{mode === 'uqload' ? 'UQLOAD' : mode === 'doodstream' ? 'DoodStream' : mode === 'filemoon' ? 'FileMoon' : mode === 'streamtape' ? 'Streamtape' : 'Any Embed Link'}</button>)}</div>
      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="p-6 rounded-3xl bg-[#0a0a0a] border border-white/10 space-y-4"><div><label className="block text-sm font-bold text-white mb-2">Title</label><input value={title} onChange={(e)=>setTitle(e.target.value)} className="w-full px-4 py-3 rounded-xl bg-black border border-white/10 text-white focus:outline-none focus:ring-2 focus:ring-amber-500/50" placeholder="Video title" /></div><div><label className="block text-sm font-bold text-white mb-2">Description</label><textarea value={description} onChange={(e)=>setDescription(e.target.value)} className="w-full h-24 px-4 py-3 rounded-xl bg-black border border-white/10 text-white focus:outline-none focus:ring-2 focus:ring-amber-500/50" placeholder="Optional description" /></div><div><label className="block text-sm font-bold text-white mb-2">Category</label><select value={categoryId} onChange={(e)=>setCategoryId(e.target.value)} className="w-full px-4 py-3 rounded-xl bg-black border border-white/10 text-white"><option value="">No category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div>
        {uploadMode === 'filemoon' && <div className="p-6 rounded-3xl bg-[#0a0a0a] border border-white/10 space-y-3"><label className="block text-sm font-bold text-white">FileMoon Account</label><select value={filemoonAccount} onChange={(e)=>setFilemoonAccount(e.target.value === '2' ? '2' : '1')} disabled={isUploading} className="w-full px-4 py-3 rounded-xl bg-black border border-white/10 text-white"><option value="1">Account 1</option><option value="2">Account 2</option></select><p className="text-xs text-zinc-500">The selected account's API key stays server-side on Railway.</p></div>}
        {uploadMode === 'embed' ? <div className="p-6 rounded-3xl bg-[#0a0a0a] border border-white/10 space-y-3"><label className="block text-sm font-bold text-white">Any Embed Link</label><p className="text-xs text-zinc-400">Paste an external iframe embed URL or full iframe code. It will use its own isolated embed player.</p><textarea value={embedInput} onChange={(e)=>setEmbedInput(e.target.value)} className="w-full h-28 px-4 py-3 rounded-xl bg-black border border-white/10 text-white" placeholder={'https://example.com/embed/abc123 or <iframe src="..."></iframe>'} /></div> : !selectedFile ? <div onDragOver={(e)=>{e.preventDefault();setIsDragging(true)}} onDragLeave={()=>setIsDragging(false)} onDrop={handleDrop} onClick={()=>fileInputRef.current?.click()} className={`border border-dashed rounded-3xl p-10 text-center cursor-pointer transition-all ${isDragging ? 'border-amber-400 bg-amber-500/10' : 'border-white/10 hover:border-white/20 bg-[#0a0a0a]'}`}><input ref={fileInputRef} type="file" accept="video/mp4,video/webm,video/quicktime,video/x-matroska" onChange={(e)=>handleFileSelect(e.target.files?.[0])} className="hidden" /><div className="w-16 h-16 rounded-2xl bg-[#141414] border border-white/10 text-amber-400 flex items-center justify-center mx-auto mb-4"><Upload className="w-8 h-8" /></div><h3 className="font-bold text-base text-white">Select or drag a video file here</h3><p className="text-xs text-zinc-400 mt-1">MP4, WebM, MOV, or MKV up to 1GB</p><div className="mt-4 inline-flex items-center px-3 py-1 rounded-full bg-[#161616] border border-white/10 text-[11px] text-zinc-300">{providerLabel} API • Admin only</div></div> : <div className="p-6 rounded-3xl bg-[#0a0a0a] border border-white/10 flex items-center justify-between gap-4"><div className="min-w-0"><p className="font-semibold truncate">{selectedFile.name}</p><p className="text-xs text-zinc-500">{(selectedFile.size/1024/1024).toFixed(1)} MB</p></div><button type="button" onClick={()=>setSelectedFile(null)} className="p-2 rounded-lg hover:bg-white/10"><X className="w-5 h-5" /></button></div>}
        {error && <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-sm text-red-300 break-words">{error}</div>}{success && <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-sm text-emerald-300">{success}</div>}
        {embedLink && <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20"><p className="text-xs text-amber-300 mb-2">Unique CornMM Embed Link</p><div className="flex gap-2"><input readOnly value={embedLink} className="flex-1 min-w-0 px-3 py-2 rounded-lg bg-black border border-white/10 text-xs text-white" /><button type="button" onClick={()=>navigator.clipboard?.writeText(embedLink)} className="px-3 py-2 rounded-lg bg-amber-500 text-black text-xs font-bold">Copy</button></div></div>}
        <button type="submit" disabled={isUploading || isSyncing} className="w-full py-4 rounded-2xl bg-amber-500 text-black font-black disabled:opacity-50 flex items-center justify-center gap-2">{isUploading ? <><Loader2 className="w-5 h-5 animate-spin" /> Saving...</> : <><LinkIcon className="w-5 h-5" /> {uploadMode === 'embed' ? 'Add Embed Link' : `Upload to ${providerLabel}`}</>}</button>
      </form>
    </div></div>
  );
}
