import React, { Suspense, lazy } from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider } from './context/AuthContext';
import { NotificationProvider } from './context/NotificationContext';
import { SEO } from './components/SEO';
import { PWAInstallPrompt } from './components/PWAInstallPrompt';
import { AgeGate } from './components/AgeGate';
import { AppLayout } from './components/layout/AppLayout';
import { HomePage } from './pages/HomePage';
import { TrendingPage } from './pages/TrendingPage';
import { LatestPage } from './pages/LatestPage';
import { CategoriesPage } from './pages/CategoriesPage';
import { CategoryPage } from './pages/CategoryPage';
import { SearchPage } from './pages/SearchPage';
import { WatchPage } from './pages/WatchPage';
import { CreatorProfilePage } from './pages/CreatorProfilePage';
import { LoginPage } from './pages/LoginPage';
import { TermsPage, PrivacyPage, DmcaPage, GuidelinesPage, ContactPage } from './pages/LegalPages';
const UploadPage=lazy(()=>import('./pages/UploadPage'));
const UserDashboardPage=lazy(()=>import('./pages/UserDashboardPage'));
const EditVideoPage=lazy(()=>import('./pages/EditVideoPage'));
const WatchHistoryPage=lazy(()=>import('./pages/WatchHistoryPage'));
const FavoritesPage=lazy(()=>import('./pages/FavoritesPage'));
const SettingsPage=lazy(()=>import('./pages/SettingsPage'));
const AdminDashboardPage=lazy(()=>import('./pages/AdminDashboardPage').then((module)=>({default:module.AdminDashboardPage})));
const RegisterPage=lazy(()=>import('./pages/RegisterPage'));
const ForgotPasswordPage=lazy(()=>import('./pages/ForgotPasswordPage'));
const PageLoader=()=> <div className="min-h-[40vh] flex items-center justify-center"><div className="w-8 h-8 border-4 border-amber-500 border-t-transparent rounded-full animate-spin"/></div>;
export const App:React.FC=()=> <BrowserRouter><SEO/><NotificationProvider><AuthProvider><AgeGate><Suspense fallback={<PageLoader/>}><Routes><Route path="/" element={<AppLayout/>}><Route index element={<HomePage/>}/><Route path="trending" element={<TrendingPage/>}/><Route path="latest" element={<LatestPage/>}/><Route path="categories" element={<CategoriesPage/>}/><Route path="category/:slug" element={<CategoryPage/>}/><Route path="search" element={<SearchPage/>}/><Route path="watch/:id" element={<WatchPage/>}/><Route path="creator/:username" element={<CreatorProfilePage/>}/><Route path="upload" element={<UploadPage/>}/><Route path="dashboard" element={<UserDashboardPage/>}/><Route path="edit/:id" element={<EditVideoPage/>}/><Route path="history" element={<WatchHistoryPage/>}/><Route path="favorites" element={<FavoritesPage/>}/><Route path="settings" element={<SettingsPage/>}/><Route path="admin" element={<AdminDashboardPage/>}/><Route path="corn-admin-login" element={<LoginPage/>}/><Route path="register" element={<RegisterPage/>}/><Route path="forgot-password" element={<ForgotPasswordPage/>}/><Route path="terms" element={<TermsPage/>}/><Route path="privacy" element={<PrivacyPage/>}/><Route path="dmca" element={<DmcaPage/>}/><Route path="guidelines" element={<GuidelinesPage/>}/><Route path="contact" element={<ContactPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Route></Routes></Suspense><PWAInstallPrompt/></AgeGate></AuthProvider></NotificationProvider></BrowserRouter>;
export default App;
